apiVersion: v1
kind: Service
metadata:
  name: ruby-app-service
  labels:
    app: ruby-app 
spec:
  selector:
    app: ruby-app

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer
